### ISSUE TITLE
Compatibility with Python3

### ISSUE THREAD

**Issue by tombasche** [hyperwallet/python-sdk#4]
Hi,

Importing `hyperwallet` causes the following to happen in Python 3.5:
```
>>> import hyperwallet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tasche/penny/venv/lib/python3.5/site-packages/hyperwallet/__init__.py", line 33, in <module>
    from .api import Api                                                     # noqa
  File "/home/tasche/penny/venv/lib/python3.5/site-packages/hyperwallet/api.py", line 5, in <module>
    from config import SERVER
ImportError: No module named 'config'
```

I'm wondering if this is compatibility or a known issue with installation?

Cheers.

**Comment by cjacobsen-hw** [comment]
The SDK has been updated, and the tests are now passing.
